steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/eu-legislation-api-v2'
      - '.'
    dir: 'junction-2025'
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/eu-legislation-api-v2'
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'eu-legislation-api-v2'
      - '--image'
      - 'gcr.io/$PROJECT_ID/eu-legislation-api-v2'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '4Gi'
      - '--cpu'
      - '2'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'GCP_PROJECT_ID=nimble-granite-478311-u2,GCP_LOCATION=europe-west1,METADATA_FILE=metadata_store_all.pkl,APP_ENV=production'

images:
  - 'gcr.io/$PROJECT_ID/eu-legislation-api-v2'

timeout: '1800s'
options:
  machineType: 'E2_HIGHCPU_8'
